/**
 * @file crm/admin/js/modules/admin-kanban.js
 * Global Kanban Board & Task Management Module.
 * Biedt drag-and-drop sprint management, taakmodals en status updates.
 * Creation+Alt+Fix CRM (2026/2027)
 */

import { doc, updateDoc } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";
import { escapeHtml } from "../../../js/firebase-config.js";
import { Toast } from "../../../js/core/toast.js";

/**
 * Initialiseert event listeners voor het Kanban bord
 * @param {Array<Object>} getProjectsFn Functie die actuele projecten retourneert
 * @param {Object} db Firestore instantie
 * @param {Function} [onTaskChanged] Callback bij wijzigingen
 */
export function setupKanbanListeners(getProjectsFn, db, onTaskChanged) {
    document.getElementById('btn-open-kanban-task-modal')?.addEventListener('click', () => {
        openGlobalTaskModal(getProjectsFn());
    });

    document.getElementById('global-add-task-form')?.addEventListener('submit', async (e) => {
        await saveGlobalTask(e, getProjectsFn(), db, onTaskChanged);
    });
}

/**
 * Rendert alle kaarten in de 4 kolommen (To Do, In Behandeling, Review, Voltooid)
 * @param {Array<Object>} projectsList 
 * @param {Object} db Firestore instantie
 * @param {Function} [onTaskChanged] Callback na verplaatsen
 */
export function renderKanbanBoard(projectsList, db, onTaskChanged) {
    const todoList = document.getElementById('list-kanban-todo');
    const inprogressList = document.getElementById('list-kanban-inprogress');
    const reviewList = document.getElementById('list-kanban-review');
    const doneList = document.getElementById('list-kanban-done');

    if (!todoList || !inprogressList || !reviewList || !doneList) return;

    // Reset Containers
    todoList.innerHTML = '';
    inprogressList.innerHTML = '';
    reviewList.innerHTML = '';
    doneList.innerHTML = '';

    const allTasks = [];

    // Aggregeer taken uit alle actieve projecten
    (projectsList || []).forEach(p => {
        const clientName = p.client || p.companyName || 'Onbekend Project';
        const projectTasks = p.tasks || [];

        if (projectTasks.length === 0) {
            let defaultStatus = 'todo';
            if (p.status && typeof p.status === 'string') {
                if (p.status.includes('Ontwikkeling') || p.status.includes('Design')) defaultStatus = 'inprogress';
                if (p.status.includes('Wacht op Akkoord')) defaultStatus = 'review';
                if (p.status.includes('Opgeleverd') || p.status.includes('Livegang')) defaultStatus = 'done';
            }

            allTasks.push({
                id: 'gen_' + p.id,
                projectId: p.id,
                clientName: clientName,
                title: `${p.service || 'Project'} Oplevering & Coördinatie`,
                priority: 'medium',
                status: defaultStatus,
                dueDate: p.date || null,
                isAutoGenerated: true
            });
        } else {
            projectTasks.forEach(t => {
                let status = t.status || (t.completed ? 'done' : 'todo');
                if (status === 'in_progress') status = 'inprogress';
                allTasks.push({
                    ...t,
                    projectId: p.id,
                    clientName: clientName,
                    status: status
                });
            });
        }
    });

    let cTodo = 0, cInprogress = 0, cReview = 0, cDone = 0;

    const createKanbanCard = (t) => {
        const card = document.createElement('div');
        card.className = 'kanban-card';

        let priorityClass = 'medium';
        if (t.priority === 'high') priorityClass = 'high';
        if (t.priority === 'low') priorityClass = 'low';
        const priorityLabel = t.priority === 'high' ? 'Hoog' : (t.priority === 'low' ? 'Laag' : 'Gemiddeld');

        let deadlineHtml = '';
        if (t.dueDate) {
            const today = new Date().toISOString().slice(0, 10);
            const isOverdue = t.status !== 'done' && t.dueDate < today;
            deadlineHtml = `<span class="deadline-tag ${isOverdue ? 'overdue' : ''}"><i class="fas fa-calendar-alt"></i> ${escapeHtml(t.dueDate)}</span>`;
        }

        const safeProject = escapeHtml(t.clientName);
        const safeTitle = escapeHtml(t.title);
        const safeProjectId = escapeHtml(t.projectId);

        card.innerHTML = `
            <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px;">
                <span class="kanban-project-tag" title="${safeProject}">${safeProject}</span>
                <span class="priority-pill ${priorityClass}">${priorityLabel}</span>
            </div>
            <div class="kanban-card-title">${safeTitle}</div>
            <div class="kanban-card-meta">
                ${deadlineHtml}
                <a href="project.html?id=${safeProjectId}" class="btn btn-sm" style="background: rgba(99,102,241,0.15); color: var(--color-primary-light); padding: 2px 6px; font-size: 0.72rem; border-radius: 4px; text-decoration: none;" title="Open Project Werkplek">
                    <i class="fas fa-external-link-alt"></i> Open
                </a>
            </div>
            <div class="kanban-card-actions">
                <label style="font-size: 0.7rem; color: var(--color-text-secondary);">Status:</label>
                <select class="admin-input kanban-status-select" style="padding: 2px 6px; font-size: 0.75rem; margin: 0; width: auto; cursor: pointer;">
                    <option value="todo" ${t.status === 'todo' ? 'selected' : ''}>To Do</option>
                    <option value="inprogress" ${t.status === 'inprogress' ? 'selected' : ''}>In Behandeling</option>
                    <option value="review" ${t.status === 'review' ? 'selected' : ''}>Review</option>
                    <option value="done" ${t.status === 'done' ? 'selected' : ''}>Voltooid</option>
                </select>
            </div>
        `;

        card.querySelector('.kanban-status-select')?.addEventListener('change', (e) => {
            moveKanbanTask(projectsList, db, t.projectId, t.id, e.target.value, onTaskChanged);
        });

        return card;
    };

    allTasks.forEach(t => {
        const card = createKanbanCard(t);
        if (t.status === 'inprogress') {
            inprogressList.appendChild(card);
            cInprogress++;
        } else if (t.status === 'review') {
            reviewList.appendChild(card);
            cReview++;
        } else if (t.status === 'done') {
            doneList.appendChild(card);
            cDone++;
        } else {
            todoList.appendChild(card);
            cTodo++;
        }
    });

    const setBadge = (id, count) => {
        const el = document.getElementById(id);
        if (el) el.innerText = String(count);
    };

    setBadge('count-kanban-todo', cTodo);
    setBadge('count-kanban-inprogress', cInprogress);
    setBadge('count-kanban-review', cReview);
    setBadge('count-kanban-done', cDone);
}

/**
 * Verplaatst een taak naar een andere statuskolom en synchroniseert met Firestore
 */
export async function moveKanbanTask(projectsList, db, projectId, taskId, targetStatus, onTaskChanged) {
    const project = (projectsList || []).find(p => p.id == projectId);
    if (!project) return;

    let tasks = project.tasks || [];

    if (String(taskId).startsWith('gen_')) {
        const newTask = {
            id: 'task_' + Date.now(),
            title: `${project.service || 'Project'} Oplevering & Deliverables`,
            status: targetStatus,
            completed: targetStatus === 'done',
            priority: 'medium',
            createdAt: new Date().toISOString()
        };
        tasks = [newTask];
    } else {
        tasks = tasks.map(t => {
            if (t.id === taskId) {
                return {
                    ...t,
                    status: targetStatus,
                    completed: targetStatus === 'done',
                    completedAt: targetStatus === 'done' ? new Date().toISOString() : null
                };
            }
            return t;
        });
    }

    project.tasks = tasks;
    renderKanbanBoard(projectsList, db, onTaskChanged);

    if (db && projectId) {
        try {
            await updateDoc(doc(db, "projects", String(projectId)), { tasks: tasks });
            Toast.show({ title: "Taakstatus bijgewerkt", type: "success", duration: 2500 });
        } catch (err) {
            console.error("Fout bij updaten kanban taak:", err);
            Toast.show({ title: "Fout bij opslaan taak", message: err.message, type: "error" });
        }
    }

    if (typeof onTaskChanged === 'function') {
        onTaskChanged();
    }
}

/**
 * Opent de modal om project-overstijgend een taak toe te voegen
 */
export function openGlobalTaskModal(projectsList = []) {
    const select = document.getElementById('global-task-project');
    if (!select) return;

    select.innerHTML = '';
    if (projectsList.length === 0) {
        select.innerHTML = '<option value="">Geen actieve projecten beschikbaar</option>';
    } else {
        projectsList.forEach(p => {
            const opt = document.createElement('option');
            opt.value = p.id;
            opt.innerText = `${p.client || p.companyName || 'Project'} (${p.service || 'Algemeen'})`;
            select.appendChild(opt);
        });
    }

    const titleEl = document.getElementById('global-task-title');
    const dateEl = document.getElementById('global-task-date');
    if (titleEl) titleEl.value = '';
    if (dateEl) dateEl.value = '';
    document.getElementById('task-modal')?.classList.remove('hidden');
}

/**
 * Slaat een nieuwe globale taak op
 */
export async function saveGlobalTask(e, projectsList, db, onTaskChanged) {
    if (e && typeof e.preventDefault === 'function') e.preventDefault();
    const projectSelect = document.getElementById('global-task-project');
    const titleInput = document.getElementById('global-task-title');
    const dateInput = document.getElementById('global-task-date');
    const prioritySelect = document.getElementById('global-task-priority');

    const projectId = projectSelect ? projectSelect.value : null;
    const title = titleInput ? titleInput.value.trim() : '';
    const dueDate = dateInput ? dateInput.value : '';
    const priority = prioritySelect ? prioritySelect.value : 'medium';

    if (!projectId || !title) return;

    const project = (projectsList || []).find(p => p.id == projectId);
    if (!project) return;

    const newTask = {
        id: 'task_' + Date.now(),
        title: title,
        dueDate: dueDate || null,
        priority: priority || 'medium',
        status: 'todo',
        completed: false,
        createdAt: new Date().toISOString()
    };

    const updatedTasks = [...(project.tasks || []), newTask];
    project.tasks = updatedTasks;

    document.getElementById('task-modal')?.classList.add('hidden');
    renderKanbanBoard(projectsList, db, onTaskChanged);

    if (db && projectId) {
        try {
            await updateDoc(doc(db, "projects", String(projectId)), { tasks: updatedTasks });
            Toast.show({ title: "Taak toegevoegd", message: `"${title}" gekoppeld aan ${project.client || 'project'}`, type: "success" });
        } catch (err) {
            console.error("Fout bij opslaan taak:", err);
            Toast.show({ title: "Fout bij opslaan", message: err.message, type: "error" });
        }
    }

    if (typeof onTaskChanged === 'function') {
        onTaskChanged();
    }
}
